app_home:
    path: /
    controller: App\Controller\HomeController::index

app_about:
    path: /about
    controller: App\Controller\AboutController::index

app_project:
    path: /project
    controller: App\Controller\ProjectController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register